### ISSUE TITLE
Module names with capital names quoted with ' (single quote) are html esacped

### ISSUE THREAD

**Issue by falkevik** [lrascao/rebar3_appup_plugin#20]
Module names in appup like "'APOLLO-PDU-Descriptions'" are generated as "{load_module,&#39;APOLLO-PDU-Descriptions&#39;,..." which can not be parsed by relup.

The reason seems to be that the generator uses templates and bbmustasch to render the appup.
And bbmustach does html escaping on single quotes.

in bbmustach.erl
%% @see escape/1
-spec escape_char(0..16#FFFF) -> binary().
escape_char($<) -> <<"&lt;">>;
escape_char($>) -> <<"&gt;">>;
escape_char($&) -> <<"&amp;">>;
escape_char($") -> <<"&quot;">>;
escape_char($') -> <<"&#39;">>;
escape_char($/) -> <<"&#x2F;">>;
escape_char($`) -> <<"&#x60;">>;
escape_char($=) -> <<"&#x3D;">>;
escape_char(C)  -> <<C:8>>.

**Comment by lrascao** [comment]
The latest bbmustache release supports escape disabling (https://github.com/soranoba/bbmustache/releases/tag/v1.5.0), maybe this fixes the issue, i'll try and build a new test for this case

**Comment by falkevik** [comment]
That should fix the issue.
Thanks!

**Comment by lrascao** [comment]
closing via #21
