### ISSUE TITLE
appup generate creates appup files even if appup compile has already created them

### ISSUE THREAD

**Issue by tothlac** [lrascao/rebar3_appup_plugin#23]
https://github.com/lrascao/rebar3_appup_plugin/blob/3b8c39ed7ec8095c2fd1d83a37f489a28ba127c1/src/rebar3_appup_generate.erl#L272

In the above mentioned line the proplists:delete tries to operate on the following structures:

 First: '"wsa"'
 UpgradedApps: '[{upgrade,dapp,
     {"0.1.38+build.134.ref8cda303",
      "0.1.40"}},
    {upgrade,wsa,
     {"0.0.28+build.98.refae382b5",
      "0.0.29"}},
    {upgrade,gwb,{"0.1.6","0.1.9"}},
    {upgrade,urbis,{"0.1.6","0.1.9"}},
    {upgrade,olog,{"0.0.7","0.0.8"}}]'

It will fail to delete the app from the list as it is not a proplist, so appup generate will create appup files for all modified applications which is not the expected behaviour.

Using 
List = lists:keydelete(list_to_atom(First), 2, UpgradedApps),
in the mentioned line fixes the issue.

**Comment by lrascao** [comment]
this definitely looks like a bug, i'll take a look soon

**Comment by lrascao** [comment]
closing via #25
