### ISSUE TITLE
SVN rebar3_appup_plugin

### ISSUE THREAD

**Issue by RAMAABHI** [lrascao/rebar3_appup_plugin#27]
Hi ,

I am trying to use this plugin for SVN code base. But when we are doing general appup, the beam_lib:cmp_dirs is listing all the files as changed.

Is this due to path changes.

**Comment by lrascao** [comment]
the path shouldn't matter when comparing, what is the sequence of commands that you are issuing?

**Comment by RAMAABHI** [comment]
Hi can i do rebar3 appup plugin for release handling from SVN. SVN is not a centralised repository like git. 

So for example my application structure is as below
application
|---trunk
|---branch
      |--- develop
      |---- feature
|---tags

Is there any sample to check for the supportability of this approach?

**Comment by lrascao** [comment]
@parmar7725274 has an example going using SVN at https://svn.riouxsvn.com/erl_experiment, take a look, maybe he can give you a hand with SVN specific stuff, please re-open if other issues come up
