### ISSUE TITLE
Can't make relup

### ISSUE THREAD

**Issue by msilvestre** [lrascao/rebar3_appup_plugin#28]
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump
===> Uncaught error: function_clause
===> Stack trace to the error location:
[{rebar3_appup_generate,select_behaviour,
                        [[gen_server,poolgirl_worker]],

**Comment by lrascao** [comment]
The plugin should drop all unknown behaviours and only process those that it knows

**Comment by lrascao** [comment]
closing via #34
