### ISSUE TITLE
Old and buggy version in pkg

### ISSUE THREAD

**Issue by tothlac** [lrascao/rebar3_appup_plugin#43]
Hi!

Some weeks ago I've reported a problem https://github.com/lrascao/rebar3_appup_plugin/issues/24

It has been already fixed by this commit:  https://github.com/lrascao/rebar3_appup_plugin/commit/7fc476694350d6bf8d9e2323caf86128ffe57345

The problem is that the current pkg version (2.3.0) still has this bug as it was released some weeks ago.

We've started to use the current git version in our projects, but the version we use in production still uses pkg, and unfortunately because of this we can't locally release that version when we want to upgrade.

Can you create a new pkg version containing this fix? It would be quite urgent because without this we can't release our new version.

**Comment by lrascao** [comment]
Hi, `2.4.0` has been pushed to hex and tagged

**Comment by zsoci** [comment]
Thanks Luis for the prompt action. It helps us a lot!

**Comment by tothlac** [comment]
Thanks for the quick fix! This is a big help for us!
