### ISSUE TITLE
Can not generate appup

### ISSUE THREAD

**Issue by vfsoraki** [lrascao/rebar3_appup_plugin#6]
I am struggling to get an upgrade release with the appup plugin.
I have followed https://github.com/lrascao/rebar3_appup_plugin/blob/develop/doc/UPGRADE_DOWNGRADE.md exactly, but when I'm trying to run `rebar3 appup generate` I get this error

> ===> please specify the previous release full path

and running `rebar3 appup generate -p _build/default/rel/relapp/` gives this error

> ===> current ("1.0.12") and previous ("1.0.12") .rel versions match

How is it done correctly?

**Comment by lrascao** [comment]
Can you check the following:

1. the version of the plugin you're on (latest is 2.0.2)
2. are you using relapp1 example release or one of your own?
3. please post the output when running in debug (DEBUG=1 rebar3 appup generate)

**Comment by vfsoraki** [comment]
1. Looking at `_build/default/plugins/rebar3_appup_plugin/src/rebar3_appup_plugin.app.src`, seems like version is `1.1.1`. I just added `{plugins, [rebar3_appup_plugin]}.` to my `rebar.config`, and it was automatically installed. How can I specify the latest version? README of plugin also just tells to add this.
2. Yes, I'm using the example release.
3. Here it is, not much information I suppose

> ===> Expanded command sequence to be run: []
> ===> Expanded command sequence to be run: [{appup,generate}]
> ===> opts: []
> 
> ===> release name: "relapp"
> ===> please specify the previous release full path
>

**Comment by lrascao** [comment]
hm.. you should be on 2.0.2 (you always get the latest if you don't specify anything), can you do a `rebar3 update` and then try again?

**Comment by vfsoraki** [comment]
Hmmm.

`rebar3 update && rebar3 upgrade` did not find any new version. Still the same error.

I deleted `_build` folder, and in the next run, rebar3 found version `2.0.2` correctly. Not sure what happened, but it worked this time.

Thanks!

**Comment by lrascao** [comment]
cool, no problem
i've created a gitter, please join if you have feedback and/or problems
https://gitter.im/rebar3-appup-plugin/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link
