### ISSUE TITLE
Appup file generated by rebar3_appup_generate contains all files if only the compile options change

### ISSUE THREAD

**Issue by tothlac** [lrascao/rebar3_appup_plugin#66]
The plugin uses beam_lib:cmp_dirs/2 to get the list of changed files. It works well if the beam files in the two releases
were compiled using the same erl_opts flag. Unfortunately for instance if I add option deterministic to erl_opts the plugin thinks
all files were changed. 

Unfortunately, we have experienced this problem between two releases. Only two files have been changed but hundreds of files were added to the appup file.

Using a modified version of beam_lib:cmp_dirs which filters out some attributes from the abstract code should be able to fix this problem.

**Comment by tothlac** [comment]
Check this pull request. I've tried it and looks like it fixes the issue. Maybe it should be tested by changing different compile options as well.

**Comment by lrascao** [comment]
closing via #67 
thanks!
