### ISSUE TITLE
Adding new supervisor

### ISSUE THREAD

**Issue by systream** [lrascao/rebar3_appup_plugin#69]
I would like to add a new supervisor to my existing supervisor, but it seems that the supervisors are ignored in supervisor_spec. 

https://github.com/lrascao/rebar3_appup_plugin/blob/develop/src/rebar3_appup_generate.erl#L655

Is there some particular reason why it only tracks workers?

**Comment by lrascao** [comment]
Honestly I don't remember, it's been a long time since I wrote this, I suppose you can try it out and see what happens

**Comment by systream** [comment]
Cool, thanks.
