### ISSUE TITLE
Insert application version in appup

### ISSUE THREAD

**Issue by sirihansen** [lrascao/rebar3_appup_plugin#7]
My application has a hardcoded .appup.src like this:

{%VSN%,
[{<<".">>,[{restart_application, MyApp}]}],
[{<<".">>,[{restart_application, MyApp}]}]
}.

I used to have a vsn.mk file which defined the current version, and my build system used this to replace %VSN% with the correct version string. When converting to rebar3 builds, I need an different way to insert the version string. In my app.src I use {vsn,git}.

I have (successfully) used the following appup.src:

_ = application:load(MyApp),
{ok,Vsn} = application:get_key(MyApp,vsn),
{Vsn,
[{<<".">>,[{restart_application, MyApp}]}],
[{<<".">>,[{restart_application, MyApp}]}]
}.

but I think that it might not be a good solution in all cases?

**Comment by lrascao** [comment]
latest develop (50c7d5b7) now supports templates .appup.src files, could you please give it a try? if all is good i'll cut a new release and push it to hex. 
The templated .appup.src is based on mustache so in the example above you need to change it to:
````
{"{{vsn}}",
[{<<".">>,[{restart_application, MyApp}]}],
[{<<".">>,[{restart_application, MyApp}]}]
}.
````

to try out the develop branch locally (as described [here](http://www.rebar3.org/docs/dependencies#checkout-dependencies)) you have to:

- clone the plugin to a folder of your choice
- in your project create a `_checkouts/` folder
- create a symlink in `_checkouts/ to the plugin cloned repo

**Comment by sirihansen** [comment]
Thanks! seems to work fine!

**Comment by lrascao** [comment]
Nice, I'll cut the next release asap

**Comment by lrascao** [comment]
`2.1.0` has been pushed to hex
